# Generated by Django 5.1 on 2024-09-03 20:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='contato_celular',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='info',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 3, 17, 31, 3, 308068)),
        ),
        migrations.AddField(
            model_name='info',
            name='empresa',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='info',
            name='motivo',
            field=models.CharField(blank=True, max_length=1555),
        ),
        migrations.AddField(
            model_name='info',
            name='produto_de_interesse',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
