# Generated by Django 5.1 on 2024-09-03 20:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_info_contato_celular_info_data_info_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 3, 17, 33, 8, 801941)),
        ),
    ]
