# Generated by Django 5.1 on 2024-10-23 19:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_info_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 23, 16, 36, 49, 641045)),
        ),
    ]
